.code
basicTrfAsm PROC
;RCX ma adres pocz¹tku, RDX ma adres koñca zakresu
;RCX s³u¿y jako "iterator"
;SIL (8-bitowa czêœæ RSI) to bufor
XOR RAX, RAX ;Zerowanie akumulatora
MYLOOP:
	mov SIL, BYTE PTR [RCX]
	add SIL, 100
	MOV [RCX], SIL
	CMP RCX, RDX
	JE OVER
	INC RCX
	JMP MYLOOP
OVER:
	mov RAX, 1
	ret
basicTrfAsm endp
gaussTrfAsm PROC
;RCX ma adres pocz¹tku, RDX ma adres koñca zakresu
;RCX s³u¿y jako "iterator"
;R8 przechowuje szerokoœæ obrazu
;SIL (8-bitowa czêœæ RSI) to bufor
XOR RAX, RAX ;Zerowanie akumulatora
ADD R8, 4
MOV R9, RCX
MOV RSI, R8
MOV RDI, R8
IMUL RSI, RSI, 6
IMUL RDI, RDI, 3
HORIZONTAL:
	MOVZX R10, BYTE PTR [RCX - 6]
	MOVD XMM0, R10d
	MOV R11, [RCX-6]
	MOV RAX, R10
	MOVZX R10, BYTE PTR [RCX - 3]
	MOV R11, [RCX-3]
	IMUL R10, R10, 4
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX]
	MOV R11, [RCX]
	IMUL R10, R10, 6
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX + 3]
	MOV R11, [RCX+3]
	IMUL R10, R10, 4
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX + 6]
	MOV R11, [RCX+6]
	ADD RAX, R10
	SHR RAX, 4
	MOV [RCX], AL
	CMP RCX, RDX
	JE TRANSITION
	INC RCX
	JMP HORIZONTAL
TRANSITION:
	MOV RCX, R9
VERTICAL:
	MOV R15, RCX
	SUB R15, RSI
	MOVZX R10, BYTE PTR [R15]
	MOV RAX, R10
	MOV R15, RCX
	SUB R15, RDI
	MOVZX R10, BYTE PTR [R15]
	IMUL R10, R10, 4
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX]
	IMUL R10, R10, 6
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX+RDI]
	IMUL R10, R10, 4
	ADD RAX, R10
	MOVZX R10, BYTE PTR [RCX+RSI]
	ADD RAX, R10
	SHR RAX, 4
	MOV [RCX], AL
	XOR RAX, RAX
	CMP RCX, RDX
	JE OVER
	INC RCX
	JMP VERTICAL
OVER:
	mov RAX, 1
	ret
gaussTrfAsm endp
END